from collections.abc import Iterable

def open_client(path: str) -> None: ...
def open_client_read_only(path: str) -> None: ...
def put_state_hamt_nodes(
    namespace: str,
    room_prefix: bytes,
    nodes: Iterable[tuple[bytes, bytes]],
) -> None: ...
def get_auth_chain_links_batch(
    namespace: str, chain_ids: list[int]
) -> list[tuple[int, list[tuple[int, int, int]]]]: ...
def put_auth_chain_links_batch(
    namespace: str, links: list[tuple[int, int, int, int]]
) -> None: ...
def delete_auth_chain_links_batch(
    namespace: str, pairs: list[tuple[int, int]]
) -> None: ...
def get_or_create_short_ids(
    namespace: str, room_id: str, event_ids: list[str]
) -> list[int]: ...
def resolve_short_ids_to_event_ids(
    namespace: str, room_id: str, short_ids: list[int]
) -> list[str | None]: ...
def auth_chain_edges_get(
    namespace: str, room_id: str, short_ids: list[int]
) -> list[list[int] | None]: ...
def auth_chain_edges_put(
    namespace: str, room_id: str, rows: list[tuple[int, list[int]]]
) -> None: ...
def auth_chain_children_get(
    namespace: str, room_id: str, short_ids: list[int]
) -> list[list[int] | None]: ...
def auth_chain_children_append(
    namespace: str, room_id: str, rows: list[tuple[int, list[int]]]
) -> None: ...
def auth_chain_purge_room(namespace: str, room_id: str) -> None: ...
def batch_get(keys: Iterable[bytes]) -> list[tuple[bytes, bytes]]: ...
def batch_put(pairs: Iterable[tuple[bytes, bytes]]) -> None: ...
def batch_delete(keys: Iterable[bytes]) -> None: ...
def event_json_put(
    namespace: str, rows: Iterable[tuple[str, str, bytes, bytes]]
) -> None: ...
def event_json_get(
    namespace: str, event_ids: list[str]
) -> list[tuple[str, bytes | None, bytes | None]]: ...
def event_json_delete(namespace: str, event_ids: list[str]) -> None: ...
def event_json_purge_room(namespace: str, room_id: str) -> None: ...
def materialize_state_hamt(
    namespace: str,
    room_prefix: bytes,
    root_structural_hash: bytes,
    room_id: str,
) -> list[tuple[str, str, str]] | None: ...
def materialize_state_hamts(
    namespace: str,
    roots: list[tuple[bytes, bytes, str]],
) -> list[list[tuple[str, str, str]]]: ...
def lookup_state_hamts(
    namespace: str,
    queries: list[tuple[bytes, bytes, bytes, list[tuple[str, str]]]],
) -> list[list[tuple[str, str, str]]]: ...
def put_state_hamt_roots(
    namespace: str,
    room_prefix: bytes,
    roots: Iterable[tuple[int, bytes]],
) -> None: ...
def get_state_hamt_roots_for_room(
    namespace: str,
    room_prefix: bytes,
    state_groups: list[int],
) -> list[bytes | None]: ...
def get_state_hamt_roots_bulk(
    namespace: str,
    state_groups: list[int],
) -> list[tuple[bytes, bytes, str] | None]: ...
def refresh_state_hamt_collections_for_groups(
    namespace: str,
    state_groups: list[int],
) -> None: ...
def delete_state_hamt_roots_for_room(
    namespace: str,
    room_prefix: bytes,
    state_groups: list[int],
) -> None: ...
def put_room_index(namespace: str, entries: Iterable[tuple[int, bytes]]) -> None: ...
def get_room_index(namespace: str, state_groups: list[int]) -> list[bytes | None]: ...
def increment_counters_batch(pairs: Iterable[tuple[bytes, int]]) -> list[int]: ...
def sync() -> None: ...
def sync_state() -> None: ...
def sync_event_dag() -> None: ...
def sync_auth_chain() -> None: ...
